<?php
/* B³ Retreats — Content-Register: Fußzeile (Abschnitt 19).
   ERZEUGT von tools/build-registry.py aus admin/schema.json und
   content/site.json. Nicht von Hand aendern: der naechste Lauf
   ueberschreibt die Datei. Texte gehoeren in content/site.json,
   danach `python3 tools/build-registry.py`. */
return [
    'foot.brand.tagline' => [
        'group' => '19 Fußzeile',
        'label' => 'Fusszeile: Markenzeile',
        'type' => 'html',
        'hint' => 'Zwei Zeilen unter dem Logo. Zeilenumbruch als <br>, Trennpunkte als &middot;.',
        'default' => 'Body. Mind. Soul.<br>Yoga &middot; Astro &middot; Business',
    ],
    'foot.brand.dateline' => [
        'group' => '19 Fußzeile',
        'label' => 'Fusszeile: Termin und Ort',
        'type' => 'html',
        'hint' => 'Datum und Ort unter dem Logo. Zeilenumbruch als <br>, Gedankenstrich als &ndash;.',
        'default' => '08.&ndash;11. Oktober 2026<br>Spabrücken, Rheinland-Pfalz',
    ],
    'foot.nav.retreat.label' => [
        'group' => '19 Fußzeile',
        'label' => 'Fusszeile Spalte 1: Ueberschrift',
        'type' => 'text',
        'hint' => 'Ueberschrift der ersten Linkspalte.',
        'default' => 'Retreat',
    ],
    'foot.nav.retreat.programm' => [
        'group' => '19 Fußzeile',
        'label' => 'Link \'Programm\'',
        'type' => 'text',
        'hint' => 'Beschriftung des Links zum Programm-Abschnitt. Das Sprungziel ist fest.',
        'default' => 'Programm',
    ],
    'foot.nav.retreat.ort' => [
        'group' => '19 Fußzeile',
        'label' => 'Link \'Der Ort\'',
        'type' => 'text',
        'hint' => 'Beschriftung des Links zum Ort-Abschnitt. Das Sprungziel ist fest.',
        'default' => 'Der Ort',
    ],
    'foot.nav.retreat.unterkunft' => [
        'group' => '19 Fußzeile',
        'label' => 'Link \'Unterkunft & Preise\'',
        'type' => 'text',
        'hint' => 'Beschriftung des Links zur Unterkunft. Kaufmaennisches Und bitte als &amp; schreiben.',
        'default' => 'Unterkunft &amp; Preise',
    ],
    'foot.nav.retreat.team' => [
        'group' => '19 Fußzeile',
        'label' => 'Link \'Ueber uns\'',
        'type' => 'text',
        'hint' => 'Beschriftung des Links zum Team-Abschnitt. Das Sprungziel ist fest.',
        'default' => 'Über uns',
    ],
    'foot.nav.retreat.faq' => [
        'group' => '19 Fußzeile',
        'label' => 'Link \'Haeufige Fragen\'',
        'type' => 'text',
        'hint' => 'Beschriftung des Links zum FAQ-Abschnitt. Das Sprungziel ist fest.',
        'default' => 'Häufige Fragen',
    ],
    'foot.nav.legal.label' => [
        'group' => '19 Fußzeile',
        'label' => 'Fusszeile Spalte 2: Ueberschrift',
        'type' => 'text',
        'hint' => 'Ueberschrift der Rechtliches-Spalte.',
        'default' => 'Rechtliches',
    ],
    'foot.nav.legal.impressum' => [
        'group' => '19 Fußzeile',
        'label' => 'Link \'Impressum\'',
        'type' => 'text',
        'hint' => 'Beschriftung des Links auf impressum.html.',
        'default' => 'Impressum',
    ],
    'foot.nav.legal.datenschutz' => [
        'group' => '19 Fußzeile',
        'label' => 'Link \'Datenschutz\'',
        'type' => 'text',
        'hint' => 'Beschriftung des Links auf datenschutz.html.',
        'default' => 'Datenschutz',
    ],
    'foot.nav.legal.agb' => [
        'group' => '19 Fußzeile',
        'label' => 'Link \'AGB\'',
        'type' => 'text',
        'hint' => 'Beschriftung des Links auf agb.html.',
        'default' => 'AGB',
    ],
    'foot.nav.legal.kontakt' => [
        'group' => '19 Fußzeile',
        'label' => 'Link \'Kontakt\'',
        'type' => 'text',
        'hint' => 'Beschriftung des Links auf den Kontaktbereich im Impressum.',
        'default' => 'Kontakt',
    ],
    'foot.nav.legal.consent' => [
        'group' => '19 Fußzeile',
        'label' => 'Knopf \'Cookie-Einstellungen\'',
        'type' => 'text',
        'hint' => 'Beschriftung des Knopfes, der den Cookie-Hinweis erneut oeffnet.',
        'default' => 'Cookie-Einstellungen',
    ],
    'foot.booking.label' => [
        'group' => '19 Fußzeile',
        'label' => 'Fusszeile Spalte 3: Ueberschrift',
        'type' => 'text',
        'hint' => 'Ueberschrift der Buchungsspalte.',
        'default' => 'Buchung',
    ],
    'foot.booking.prices' => [
        'group' => '19 Fußzeile',
        'label' => 'Fusszeile: Preishinweis',
        'type' => 'html',
        'hint' => 'Zwei Preiszeilen. Zeilenumbruch als <br>, Eurozeichen als &euro;.',
        'default' => 'Shared House ab 1.549 &euro; pro Person<br>Friends Special 3.950 &euro; für zwei',
    ],
    'foot.booking.cta' => [
        'group' => '19 Fußzeile',
        'label' => 'Fusszeile: Knopfbeschriftung',
        'type' => 'text',
        'hint' => 'Text des Buchungsknopfes in der Fusszeile.',
        'default' => 'Meinen Platz sichern',
    ],
    'foot.legal.line' => [
        'group' => '19 Fußzeile',
        'label' => 'Fusszeile: Anbieterzeile',
        'type' => 'text',
        'hint' => 'Firmierung, Name und Anschrift. Trennpunkte als &middot; schreiben.',
        'default' => 'B³ Retreats &middot; Christina Brumm &middot; An den Nahewiesen 20, 55450 Langenlonsheim',
    ],
    'foot.legal.note' => [
        'group' => '19 Fußzeile',
        'label' => 'Fusszeile: Hinweis zur Abwicklung',
        'type' => 'text',
        'hint' => 'Kurzer Hinweis, ueber welchen Anbieter Buchung und Zahlung laufen.',
        'default' => 'Buchung und Zahlungsabwicklung über Tentary',
    ],
];
