<?php
/* B³ Retreats — Content-Register: Suchmaschine und Vorschau (Abschnitt 01).
   ERZEUGT von tools/build-registry.py aus admin/schema.json und
   content/site.json. Nicht von Hand aendern: der naechste Lauf
   ueberschreibt die Datei. Texte gehoeren in content/site.json,
   danach `python3 tools/build-registry.py`. */
return [
    'meta.title' => [
        'group' => '01 Suchmaschine und Vorschau',
        'label' => 'Seitentitel (Browser-Tab & Google)',
        'type' => 'text',
        'hint' => 'Erscheint im Browser-Tab und als blaue Überschrift bei Google. Ideal 50–60 Zeichen.',
        'default' => 'B³ Retreat für Frauen | 08.–11. Oktober 2026 in Spabrücken',
    ],
    'meta.description' => [
        'group' => '01 Suchmaschine und Vorschau',
        'label' => 'Meta-Beschreibung (Google-Vorschau)',
        'type' => 'textarea',
        'hint' => 'Der Beschreibungstext unter dem Google-Treffer. Ideal 140–160 Zeichen, mit Termin, Ort und Preis.',
        'default' => 'Vier Tage zurück zu dir: Frauen-Retreat mit Yin Yoga, Breathwork, Astrologie und Struktur vom 08.–11. Oktober 2026 in Spabrücken. Ab 1.549 € inkl. Unterkunft und Verpflegung, Ratenzahlung möglich.',
    ],
    'meta.canonical' => [
        'group' => '01 Suchmaschine und Vorschau',
        'label' => 'Kanonische Adresse der Seite',
        'type' => 'url',
        'hint' => 'Die eine offizielle Adresse dieser Seite für Suchmaschinen. Nur ändern, wenn die Domain wechselt.',
        'default' => 'https://b3-retreats.de/',
    ],
    'meta.google_site_verification' => [
        'group' => '01 Suchmaschine und Vorschau',
        'label' => 'Google-Bestätigungscode',
        'type' => 'text',
        'hint' => 'Der Code aus der Google Search Console („HTML-Tag“) — nur der Wert aus content="…", ohne den Rest der Zeile. Leer lassen entfernt die Zeile aus der Seite. Nicht löschen, solange die Search Console genutzt wird: Google prüft den Code regelmäßig nach.',
        'default' => 'rea52oRzw9FTP1FTqxqboVxYl6JjOcomWECNzU3VXcc',
    ],
    'meta.favicon.src' => [
        'group' => '01 Suchmaschine und Vorschau',
        'label' => 'Seitensymbol (Favicon im Browser-Tab)',
        'type' => 'image',
        'hint' => 'Das kleine Zeichen im Browser-Tab, in den Lesezeichen und im Verlauf. Quadratisch. Am besten eine SVG-Datei oder ein PNG ab 512 × 512 Pixel.',
        'default' => 'assets/img/favicon.svg',
    ],
    'meta.favicon.apple' => [
        'group' => '01 Suchmaschine und Vorschau',
        'label' => 'Seitensymbol für iPhone und iPad',
        'type' => 'image',
        'hint' => 'Wird verwendet, wenn jemand die Seite auf den Home-Bildschirm legt. Quadratisches PNG, 180 × 180 Pixel.',
        'default' => 'assets/img/favicon-180.png',
    ],
    'meta.og.site_name' => [
        'group' => '01 Suchmaschine und Vorschau',
        'label' => 'Website-Name beim Teilen',
        'type' => 'text',
        'hint' => 'Name der Website, den WhatsApp, Facebook & Co. über der Vorschau anzeigen.',
        'default' => 'B³ Retreats',
    ],
    'meta.og.title' => [
        'group' => '01 Suchmaschine und Vorschau',
        'label' => 'Titel beim Teilen (Social Media)',
        'type' => 'text',
        'hint' => 'Überschrift der Link-Vorschau, wenn jemand die Seite in WhatsApp, Instagram oder Facebook teilt.',
        'default' => 'B³ Retreat – Be free to be you. | 08.–11. Oktober 2026, Spabrücken',
    ],
    'meta.og.description' => [
        'group' => '01 Suchmaschine und Vorschau',
        'label' => 'Beschreibung beim Teilen (Social Media)',
        'type' => 'textarea',
        'hint' => 'Kurztext der Link-Vorschau beim Teilen. Zwei bis drei Sätze, die neugierig machen.',
        'default' => 'Vier Tage zurück zu dir, deinen Bedürfnissen und dem, was du wirklich willst. Yin Yoga, Breathwork, Astrologie und Struktur – für maximal 11 Frauen.',
    ],
    'meta.og.image' => [
        'group' => '01 Suchmaschine und Vorschau',
        'label' => 'Vorschaubild beim Teilen',
        'type' => 'image',
        'hint' => 'Bild der Link-Vorschau beim Teilen. Querformat, empfohlen 1200 × 630 Pixel.',
        'default' => 'assets/img/og-image.webp',
    ],
    'meta.jsonld.name' => [
        'group' => '01 Suchmaschine und Vorschau',
        'label' => 'Veranstaltungsname (Suchmaschinen-Daten)',
        'type' => 'text',
        'hint' => 'Offizieller Name des Retreats in den strukturierten Daten, mit denen Google das Event erkennt.',
        'default' => 'B³ Retreat – Be free to be you.',
    ],
    'meta.jsonld.start_date' => [
        'group' => '01 Suchmaschine und Vorschau',
        'label' => 'Beginn (Datum und Uhrzeit)',
        'type' => 'text',
        'hint' => 'Startzeitpunkt in technischer Schreibweise JJJJ-MM-TTThh:mm, z. B. 2026-10-08T16:00.',
        'default' => '2026-10-08T16:00',
    ],
    'meta.jsonld.end_date' => [
        'group' => '01 Suchmaschine und Vorschau',
        'label' => 'Ende (Datum und Uhrzeit)',
        'type' => 'text',
        'hint' => 'Endzeitpunkt in technischer Schreibweise JJJJ-MM-TTThh:mm, z. B. 2026-10-11T12:00.',
        'default' => '2026-10-11T12:00',
    ],
    'meta.jsonld.description' => [
        'group' => '01 Suchmaschine und Vorschau',
        'label' => 'Event-Beschreibung (Suchmaschinen-Daten)',
        'type' => 'textarea',
        'hint' => 'Kurzbeschreibung des Retreats für die Google-Event-Anzeige. Ein bis zwei Sätze, keine Anführungszeichen verwenden.',
        'default' => 'Vier Tage Frauen-Retreat mit Yin Yoga, Breathwork, Astro Energy Reading, Solfeggio-Frequenz-Reise und einer Session zu intuitiver Struktur.',
    ],
    'meta.jsonld.location.name' => [
        'group' => '01 Suchmaschine und Vorschau',
        'label' => 'Name des Veranstaltungsortes',
        'type' => 'text',
        'hint' => 'Wie die Location heißt, z. B. Anwesen Spabrücken.',
        'default' => 'Anwesen Spabrücken',
    ],
    'meta.jsonld.location.locality' => [
        'group' => '01 Suchmaschine und Vorschau',
        'label' => 'Ort',
        'type' => 'text',
        'hint' => 'Stadt oder Gemeinde des Veranstaltungsortes.',
        'default' => 'Spabrücken',
    ],
    'meta.jsonld.location.region' => [
        'group' => '01 Suchmaschine und Vorschau',
        'label' => 'Bundesland / Region',
        'type' => 'text',
        'hint' => 'Region des Veranstaltungsortes, z. B. Rheinland-Pfalz.',
        'default' => 'Rheinland-Pfalz',
    ],
    'meta.jsonld.location.country' => [
        'group' => '01 Suchmaschine und Vorschau',
        'label' => 'Land (Länderkürzel)',
        'type' => 'text',
        'hint' => 'Zweibuchstabiges Länderkürzel, DE für Deutschland, AT für Österreich, CH für die Schweiz.',
        'default' => 'DE',
    ],
    'meta.jsonld.organizer.name' => [
        'group' => '01 Suchmaschine und Vorschau',
        'label' => 'Veranstalterin (Name)',
        'type' => 'text',
        'hint' => 'Name der Veranstalterin bzw. der Marke, die das Retreat anbietet.',
        'default' => 'B³ Retreats',
    ],
    'meta.jsonld.organizer.url' => [
        'group' => '01 Suchmaschine und Vorschau',
        'label' => 'Website der Veranstalterin',
        'type' => 'url',
        'hint' => 'Vollständige Internetadresse der Veranstalterin, inklusive https://.',
        'default' => 'https://b3-retreats.de/',
    ],
    'meta.jsonld.offers.shared.name' => [
        'group' => '01 Suchmaschine und Vorschau',
        'label' => 'Angebot 1: Bezeichnung',
        'type' => 'text',
        'hint' => 'Name des ersten Buchungspakets, wie es Google anzeigt, z. B. Shared House.',
        'default' => 'Shared House',
    ],
    'meta.jsonld.offers.shared.price' => [
        'group' => '01 Suchmaschine und Vorschau',
        'label' => 'Angebot 1: Preis in Euro',
        'type' => 'number',
        'hint' => 'Nur die Zahl ohne Euro-Zeichen und ohne Punkt, z. B. 1549. Muss zum Preis im Buchungsabschnitt passen.',
        'default' => '1549',
    ],
    'meta.jsonld.offers.friends.name' => [
        'group' => '01 Suchmaschine und Vorschau',
        'label' => 'Angebot 2: Bezeichnung',
        'type' => 'text',
        'hint' => 'Name des zweiten Buchungspakets, z. B. Friends Special (2 Personen).',
        'default' => 'Friends Special (2 Personen)',
    ],
    'meta.jsonld.offers.friends.price' => [
        'group' => '01 Suchmaschine und Vorschau',
        'label' => 'Angebot 2: Preis in Euro',
        'type' => 'number',
        'hint' => 'Nur die Zahl ohne Euro-Zeichen und ohne Punkt, z. B. 3950. Muss zum Preis im Buchungsabschnitt passen.',
        'default' => '3950',
    ],
];
