<?php
/* B³ Retreats — Content-Register: Der Ort (Abschnitt 10).
   ERZEUGT von tools/build-registry.py aus admin/schema.json und
   content/site.json. Nicht von Hand aendern: der naechste Lauf
   ueberschreibt die Datei. Texte gehoeren in content/site.json,
   danach `python3 tools/build-registry.py`. */
return [
    'ort.kapitel' => [
        'group' => '10 Der Ort',
        'label' => 'Kapitelnummer Retreat-Ort',
        'type' => 'text',
        'hint' => 'Randbeschriftung, z.B. "Kapitel 07".',
        'default' => 'Kapitel 07',
    ],
    'ort.eyebrow' => [
        'group' => '10 Der Ort',
        'label' => 'Übertitel Retreat-Ort',
        'type' => 'text',
        'hint' => 'Ortsangabe über der Überschrift, z.B. "Spabrücken | Rheinland-Pfalz".',
        'default' => 'Spabrücken | Rheinland-Pfalz',
    ],
    'ort.headline' => [
        'group' => '10 Der Ort',
        'label' => 'Überschrift Retreat-Ort',
        'type' => 'text',
        'hint' => 'Hauptüberschrift des Ort-Abschnitts.',
        'default' => 'Unser Retreat-Ort',
    ],
    'ort.map.line1' => [
        'group' => '10 Der Ort',
        'label' => 'Karte – Zeile 1',
        'type' => 'text',
        'hint' => 'Zeile neben der Kartengrafik (Ort und Landkreis).',
        'default' => 'Spabrücken, Landkreis Bad Kreuznach.',
    ],
    'ort.p1' => [
        'group' => '10 Der Ort',
        'label' => 'Retreat-Ort – Absatz 1',
        'type' => 'textarea',
        'hint' => 'Erster Fließtextabsatz zum Anwesen.',
        'default' => 'Unser Retreat findet auf einem großzügigen Anwesen in Spabrücken statt. Abgelegen vom Trubel und umgeben von Feldern, Wald und kleinen Wegen ist es ein Ort, an dem man erstaunlich schnell ein bisschen langsamer wird.',
    ],
    'ort.p2' => [
        'group' => '10 Der Ort',
        'label' => 'Retreat-Ort – Absatz 2',
        'type' => 'textarea',
        'hint' => 'Zweiter Fließtextabsatz (Remise).',
        'default' => 'Das Herzstück unseres Retreats ist eine große, moderne Remise. Hier finden viele unserer Experiences statt, hier essen wir gemeinsam und wahrscheinlich entstehen hier auch einige der Gespräche, die man vorher nicht planen kann.',
    ],
    'ort.p3' => [
        'group' => '10 Der Ort',
        'label' => 'Retreat-Ort – Absatz 3',
        'type' => 'textarea',
        'hint' => 'Dritter Fließtextabsatz (Terrasse, Abende).',
        'default' => 'Bei schönem Wetter verbringen wir die Abende draußen auf der großen Holzterrasse. Von dort blickt man weit über die Landschaft und kann den Sonnenuntergang genießen, während auf dem Holzgrill unser Abendessen zubereitet wird.',
    ],
    'ort.p4' => [
        'group' => '10 Der Ort',
        'label' => 'Retreat-Ort – Absatz 4',
        'type' => 'textarea',
        'hint' => 'Vierter Fließtextabsatz (Umgebung, Wege).',
        'default' => 'Und wenn du zwischendurch raus möchtest, gehst du einfach los. Rund um das Anwesen führen Feld- und Waldwege durch die Umgebung.',
    ],
    'ort.mosaic[0].src' => [
        'group' => '10 Der Ort',
        'label' => 'Bildmosaik 1 – Bild',
        'type' => 'image',
        'hint' => 'Querformat 1600×900 px, große Kachel oben.',
        'default' => 'assets/img/ort-terrasse.webp',
    ],
    'ort.mosaic[0].alt' => [
        'group' => '10 Der Ort',
        'label' => 'Bildmosaik 1 – Alternativtext',
        'type' => 'text',
        'hint' => 'Bildbeschreibung für Screenreader.',
        'default' => 'Überdachte Terrasse mit langem Tisch, dahinter offene Felder',
    ],
    'ort.mosaic[1].src' => [
        'group' => '10 Der Ort',
        'label' => 'Bildmosaik 2 – Bild',
        'type' => 'image',
        'hint' => 'Hochformat 1000×1250 px.',
        'default' => 'assets/img/ort-sonne.webp',
    ],
    'ort.mosaic[1].alt' => [
        'group' => '10 Der Ort',
        'label' => 'Bildmosaik 2 – Alternativtext',
        'type' => 'text',
        'hint' => 'Bildbeschreibung für Screenreader.',
        'default' => 'Sonnenlicht durch die Baumkronen am Rand des Grundstücks',
    ],
    'ort.mosaic[2].src' => [
        'group' => '10 Der Ort',
        'label' => 'Bildmosaik 3 – Bild',
        'type' => 'image',
        'hint' => 'Querformat 1100×619 px.',
        'default' => 'assets/img/ort-anwesen.webp',
    ],
    'ort.mosaic[2].alt' => [
        'group' => '10 Der Ort',
        'label' => 'Bildmosaik 3 – Alternativtext',
        'type' => 'text',
        'hint' => 'Bildbeschreibung für Screenreader.',
        'default' => 'Das Anwesen mit Zypressenreihe und Sitzgruppe',
    ],
    'ort.mosaic[3].src' => [
        'group' => '10 Der Ort',
        'label' => 'Bildmosaik 4 – Bild',
        'type' => 'image',
        'hint' => 'Querformat 1100×619 px.',
        'default' => 'assets/img/ort-remise.webp',
    ],
    'ort.mosaic[3].alt' => [
        'group' => '10 Der Ort',
        'label' => 'Bildmosaik 4 – Alternativtext',
        'type' => 'text',
        'hint' => 'Bildbeschreibung für Screenreader.',
        'default' => 'Zufahrt zur Remise',
    ],
    'ort.mosaic[4].src' => [
        'group' => '10 Der Ort',
        'label' => 'Bildmosaik 5 – Bild',
        'type' => 'image',
        'hint' => 'Querformat 1100×619 px.',
        'default' => 'assets/img/ort-terrasse2.webp',
    ],
    'ort.mosaic[4].alt' => [
        'group' => '10 Der Ort',
        'label' => 'Bildmosaik 5 – Alternativtext',
        'type' => 'text',
        'hint' => 'Bildbeschreibung für Screenreader.',
        'default' => 'Lounge auf der Terrasse mit Blick über die Felder',
    ],
    'ort.mosaic[5].src' => [
        'group' => '10 Der Ort',
        'label' => 'Bildmosaik 6 – Bild',
        'type' => 'image',
        'hint' => 'Hochformat 1000×1250 px.',
        'default' => 'assets/img/ort-eingang.webp',
    ],
    'ort.mosaic[5].alt' => [
        'group' => '10 Der Ort',
        'label' => 'Bildmosaik 6 – Alternativtext',
        'type' => 'text',
        'hint' => 'Bildbeschreibung für Screenreader.',
        'default' => 'Eingangsbereich des Anwesens',
    ],
    'ort.mosaic[6].src' => [
        'group' => '10 Der Ort',
        'label' => 'Bildmosaik 7 – Bild',
        'type' => 'image',
        'hint' => 'Hochformat 1000×1250 px.',
        'default' => 'assets/img/ort-saeule.webp',
    ],
    'ort.mosaic[6].alt' => [
        'group' => '10 Der Ort',
        'label' => 'Bildmosaik 7 – Alternativtext',
        'type' => 'text',
        'hint' => 'Bildbeschreibung für Screenreader.',
        'default' => 'Überdachter Außenbereich mit Blick ins Tal',
    ],
    'ort.mosaic[7].src' => [
        'group' => '10 Der Ort',
        'label' => 'Bildmosaik 8 – Bild',
        'type' => 'image',
        'hint' => 'Hochformat 1000×1250 px.',
        'default' => 'assets/img/ort-haus.webp',
    ],
    'ort.mosaic[7].alt' => [
        'group' => '10 Der Ort',
        'label' => 'Bildmosaik 8 – Alternativtext',
        'type' => 'text',
        'hint' => 'Bildbeschreibung für Screenreader.',
        'default' => 'Überdachter Balkon mit Sitzgelegenheit',
    ],
];
