<?php
/* B³ Retreats — Content-Register: Über uns (Abschnitt 14).
   ERZEUGT von tools/build-registry.py aus admin/schema.json und
   content/site.json. Nicht von Hand aendern: der naechste Lauf
   ueberschreibt die Datei. Texte gehoeren in content/site.json,
   danach `python3 tools/build-registry.py`. */
return [
    'team.rail' => [
        'group' => '14 Über uns',
        'label' => 'Kapitelmarke Team',
        'type' => 'text',
        'hint' => 'Seitliche Kapitelnummer, z. B. „Kapitel 10“',
        'default' => 'Kapitel 10',
    ],
    'team.eyebrow' => [
        'group' => '14 Über uns',
        'label' => 'Überzeile Team',
        'type' => 'text',
        'hint' => 'Namen der Gastgeberinnen, getrennt durch &middot;',
        'default' => 'Sophie &middot; Sarah &middot; Christina',
    ],
    'team.headline' => [
        'group' => '14 Über uns',
        'label' => 'Überschrift Team',
        'type' => 'text',
        'hint' => 'Hauptüberschrift des Team-Abschnitts',
        'default' => 'Die drei Frauen hinter B³',
    ],
    'team.intro' => [
        'group' => '14 Über uns',
        'label' => 'Einleitung Team',
        'type' => 'textarea',
        'hint' => 'Gemeinsamer Einleitungsabsatz über die drei Gastgeberinnen',
        'default' => 'Drei Persönlichkeiten, drei unterschiedliche Welten und ziemlich unterschiedliche Wege haben uns hierhergebracht. Was uns verbindet, ist die Überzeugung, dass wir uns und unser Leben nicht in einzelne Schubladen aufteilen müssen.',
    ],
    'team.sophie.image.src' => [
        'group' => '14 Über uns',
        'label' => 'Foto Sophie',
        'type' => 'image',
        'hint' => 'Porträt im Hochformat 900x1125',
        'default' => 'assets/img/sophie.webp',
    ],
    'team.sophie.image.alt' => [
        'group' => '14 Über uns',
        'label' => 'Bildbeschreibung Foto Sophie',
        'type' => 'text',
        'hint' => 'Alternativtext des Porträts',
        'default' => 'Sophie Christin Braun am Feldrand',
    ],
    'team.sophie.name' => [
        'group' => '14 Über uns',
        'label' => 'Name Sophie',
        'type' => 'text',
        'hint' => 'Vollständiger Name als Überschrift des Profils',
        'default' => 'Sophie Christin Braun',
    ],
    'team.sophie.craft' => [
        'group' => '14 Über uns',
        'label' => 'Fachgebiete Sophie',
        'type' => 'text',
        'hint' => 'Arbeitsschwerpunkte, getrennt durch senkrechte Striche',
        'default' => 'Astrologie | Energiearbeit | spirituelle &amp; mediale Impulse',
    ],
    'team.sophie.text1' => [
        'group' => '14 Über uns',
        'label' => 'Sophie Absatz 1',
        'type' => 'textarea',
        'hint' => 'Erster Absatz der Selbstvorstellung',
        'default' => 'Ich bin Sophie – neugierig, intuitiv, manchmal ziemlich tiefgründig und definitiv ein kleiner Freigeist.',
    ],
    'team.sophie.text2' => [
        'group' => '14 Über uns',
        'label' => 'Sophie Absatz 2',
        'type' => 'textarea',
        'hint' => 'Zweiter Absatz der Selbstvorstellung',
        'default' => 'Ich war noch nie besonders gut darin, mich in Schubladen stecken zu lassen. Ich mag kein Schwarz-Weiß-Denken und keine fertigen Antworten.',
    ],
    'team.sophie.accent' => [
        'group' => '14 Über uns',
        'label' => 'Sophie Hervorhebung',
        'type' => 'textarea',
        'hint' => 'Hervorgehoben gesetzter Zwischensatz zwischen Absatz 2 und 3',
        'default' => 'Aber warum eigentlich? Muss das wirklich so sein?',
    ],
    'team.sophie.text3' => [
        'group' => '14 Über uns',
        'label' => 'Sophie Absatz 3',
        'type' => 'textarea',
        'hint' => 'Absatz nach der Hervorhebung, beschreibt die Arbeitsweise',
        'default' => 'Genau diese Freiheit, selbst zu denken, zu fühlen und den eigenen Weg zu gehen, möchte ich auch in meine Arbeit mitgeben. Meine Arbeit verbindet Astrologie, Energiearbeit und spirituelle sowie mediale Impulse. Im Mittelpunkt steht für mich dabei immer die Verbindung zur Quelle, zu Gott und zu unserer eigenen inneren Wahrheit.',
    ],
    'team.sophie.text4' => [
        'group' => '14 Über uns',
        'label' => 'Sophie Absatz 4',
        'type' => 'textarea',
        'hint' => 'Abschließender Absatz der Selbstvorstellung',
        'default' => 'Ich freue mich sehr auf echte Begegnungen, tiefe Gespräche, kleine Aha-Momente und darauf, diese besondere Zeit miteinander zu erleben.',
    ],
    'team.sarah.image.src' => [
        'group' => '14 Über uns',
        'label' => 'Foto Sarah',
        'type' => 'image',
        'hint' => 'Porträt im Hochformat 900x1125',
        'default' => 'assets/img/sarah.webp',
    ],
    'team.sarah.image.alt' => [
        'group' => '14 Über uns',
        'label' => 'Bildbeschreibung Foto Sarah',
        'type' => 'text',
        'hint' => 'Alternativtext des Porträts',
        'default' => 'Sarah Bernhard am Feldrand',
    ],
    'team.sarah.name' => [
        'group' => '14 Über uns',
        'label' => 'Name Sarah',
        'type' => 'text',
        'hint' => 'Vollständiger Name als Überschrift des Profils',
        'default' => 'Sarah Bernhard',
    ],
    'team.sarah.craft' => [
        'group' => '14 Über uns',
        'label' => 'Fachgebiete Sarah',
        'type' => 'text',
        'hint' => 'Arbeitsschwerpunkte, getrennt durch senkrechte Striche',
        'default' => 'Yin Yoga | Breathwork | Bodywork',
    ],
    'team.sarah.text1' => [
        'group' => '14 Über uns',
        'label' => 'Sarah Absatz 1',
        'type' => 'textarea',
        'hint' => 'Erster Absatz der Selbstvorstellung',
        'default' => 'Ich bin Sarah und begleite Menschen dabei, wieder mehr in Kontakt mit sich selbst, ihrem Körper und dem eigenen Erleben zu kommen.',
    ],
    'team.sarah.text2' => [
        'group' => '14 Über uns',
        'label' => 'Sarah Absatz 2',
        'type' => 'textarea',
        'hint' => 'Zweiter Absatz der Selbstvorstellung',
        'default' => 'Mir geht es dabei nicht darum, etwas zu erzwingen oder „wegzumachen“, sondern einen Raum zu schaffen, in dem du deinen Körper wieder wahrnehmen, zur Ruhe kommen und dich selbst ein Stück tiefer erfahren kannst.',
    ],
    'team.christina.image.src' => [
        'group' => '14 Über uns',
        'label' => 'Foto Christina',
        'type' => 'image',
        'hint' => 'Porträt im Hochformat 900x1125',
        'default' => 'assets/img/christina.webp',
    ],
    'team.christina.image.alt' => [
        'group' => '14 Über uns',
        'label' => 'Bildbeschreibung Foto Christina',
        'type' => 'text',
        'hint' => 'Alternativtext des Porträts',
        'default' => 'Christina am Feldrand',
    ],
    'team.christina.name' => [
        'group' => '14 Über uns',
        'label' => 'Name Christina',
        'type' => 'text',
        'hint' => 'Name als Überschrift des Profils',
        'default' => 'Christina',
    ],
    'team.christina.craft' => [
        'group' => '14 Über uns',
        'label' => 'Fachgebiete Christina',
        'type' => 'text',
        'hint' => 'Arbeitsschwerpunkte, getrennt durch senkrechte Striche',
        'default' => 'Strategie | Business | Struktur',
    ],
    'team.christina.text1' => [
        'group' => '14 Über uns',
        'label' => 'Christina Absatz 1',
        'type' => 'textarea',
        'hint' => 'Erster Absatz der Selbstvorstellung',
        'default' => 'Ich bin Christina – kreative Seele, Unternehmerin und ziemlich schlecht darin, mich mit einem „entweder oder“ zufriedenzugeben.',
    ],
    'team.christina.accent' => [
        'group' => '14 Über uns',
        'label' => 'Christina Hervorhebung',
        'type' => 'textarea',
        'hint' => 'Hervorgehoben gesetzter Zwischensatz nach Absatz 1',
        'default' => 'Ich will alles.',
    ],
    'team.christina.text2' => [
        'group' => '14 Über uns',
        'label' => 'Christina Absatz 2',
        'type' => 'textarea',
        'hint' => 'Absatz nach der Hervorhebung',
        'default' => 'Ich möchte mich in meinem Business verwirklichen, meine Familie und Partnerschaft lieben und leben, erfolgreich sein, frei sein und trotzdem genügend Zeit für die Menschen und Dinge haben, die mir wichtig sind.',
    ],
    'team.christina.text3' => [
        'group' => '14 Über uns',
        'label' => 'Christina Absatz 3',
        'type' => 'textarea',
        'hint' => 'Absatz zum Verhältnis von Business und Leben',
        'default' => 'Mit klassischer Work-Life-Balance konnte ich deshalb noch nie besonders viel anfangen. Mein Business steht für mich nicht auf der einen und mein Leben auf der anderen Seite. Es ist ein Teil meines Lebens, den ich liebe und den ich genauso bewusst gestalten möchte wie alle anderen Bereiche.',
    ],
    'team.christina.text4' => [
        'group' => '14 Über uns',
        'label' => 'Christina Absatz 4',
        'type' => 'textarea',
        'hint' => 'Absatz über Prioritäten und Gleichzeitigkeit',
        'default' => 'Ich glaube daran, dass die Dinge, die uns wichtig sind, gleichzeitig Platz haben dürfen. Nicht immer zu gleichen Teilen und ganz sicher nicht immer perfekt. Aber ohne uns selbst dabei ständig auf später zu verschieben.',
    ],
    'team.christina.text5' => [
        'group' => '14 Über uns',
        'label' => 'Christina Absatz 5',
        'type' => 'textarea',
        'hint' => 'Absatz über Struktur und Arbeitsweise',
        'default' => 'Dafür braucht es Struktur. Nur eben keine starren Regeln und keinen Kalender, der jede Minute kontrolliert. Ich arbeite mit einer intuitiven, lebendigen Struktur, die sich dem Leben anpassen darf und uns dabei hilft, unsere Prioritäten tatsächlich zu leben.',
    ],
    'team.christina.text6' => [
        'group' => '14 Über uns',
        'label' => 'Christina Absatz 6',
        'type' => 'textarea',
        'hint' => 'Abschließender Absatz zur Selbstverwirklichung',
        'default' => 'Denn Selbstverwirklichung bedeutet für mich nicht, immer mehr zu schaffen. Es bedeutet, ein Leben aufzubauen, das wirklich zu mir gehört.',
    ],
];
