-- B³ Retreats — Inhalte fuer die content-Tabelle.
-- ERZEUGT von tools/build-registry.py aus content/site.json.
--
-- Optional: ohne diese Datei rendert die Seite die Standardwerte aus
-- partials/registry/. MIT ihr stehen die Texte auch in der Datenbank und
-- sind damit im Panel sichtbar und bearbeitbar.
--
-- Import: admin/setup.php legt sie auf Wunsch mit an, oder in phpMyAdmin
-- nach schema.sql einlesen. Wiederholbar: bestehende Zeilen werden
-- ueberschrieben (ON DUPLICATE KEY UPDATE), nichts wird geloescht.
SET NAMES utf8mb4;

INSERT INTO `content` (`k`, `v`, `type`) VALUES
('meta.title', 'B³ Retreat für Frauen | 08.–11. Oktober 2026 in Spabrücken', 'text'),
('meta.description', 'Vier Tage zurück zu dir: Frauen-Retreat mit Yin Yoga, Breathwork, Astrologie und Struktur vom 08.–11. Oktober 2026 in Spabrücken. Ab 1.549 € inkl. Unterkunft und Verpflegung, Ratenzahlung möglich.', 'textarea'),
('meta.canonical', 'https://b3-retreats.de/', 'url'),
('meta.favicon.src', 'assets/img/favicon.svg', 'image'),
('meta.favicon.apple', 'assets/img/favicon-180.png', 'image'),
('meta.og.site_name', 'B³ Retreats', 'text'),
('meta.og.title', 'B³ Retreat – Be free to be you. | 08.–11. Oktober 2026, Spabrücken', 'text'),
('meta.og.description', 'Vier Tage zurück zu dir, deinen Bedürfnissen und dem, was du wirklich willst. Yin Yoga, Breathwork, Astrologie und Struktur – für maximal 11 Frauen.', 'textarea'),
('meta.og.image', 'assets/img/og-image.webp', 'image'),
('meta.jsonld.name', 'B³ Retreat – Be free to be you.', 'text'),
('meta.jsonld.start_date', '2026-10-08T16:00', 'text'),
('meta.jsonld.end_date', '2026-10-11T12:00', 'text'),
('meta.jsonld.description', 'Vier Tage Frauen-Retreat mit Yin Yoga, Breathwork, Astro Energy Reading, Solfeggio-Frequenz-Reise und einer Session zu intuitiver Struktur.', 'textarea'),
('meta.jsonld.location.name', 'Anwesen Spabrücken', 'text'),
('meta.jsonld.location.locality', 'Spabrücken', 'text'),
('meta.jsonld.location.region', 'Rheinland-Pfalz', 'text'),
('meta.jsonld.location.country', 'DE', 'text'),
('meta.jsonld.organizer.name', 'B³ Retreats', 'text'),
('meta.jsonld.organizer.url', 'https://b3-retreats.de/', 'url'),
('meta.jsonld.offers.shared.name', 'Shared House', 'text'),
('meta.jsonld.offers.shared.price', '1549', 'number'),
('meta.jsonld.offers.friends.name', 'Friends Special (2 Personen)', 'text'),
('meta.jsonld.offers.friends.price', '3950', 'number'),
('nav.programm', 'Programm', 'text'),
('nav.unterkunft', 'Unterkunft &amp; Preise', 'text'),
('nav.team', 'Über uns', 'text'),
('nav.cta', 'Platz sichern', 'text'),
('nav.meta.dates', '08.–11. Oktober 2026', 'text'),
('nav.meta.location', 'Spabrücken, Rheinland-Pfalz', 'text'),
('hero.meta', '08.–11. Oktober 2026 &nbsp;|&nbsp; Spabrücken', 'html'),
('hero.headline', 'Be free to be&nbsp;you.', 'html'),
('hero.lead', 'Vier Tage zurück zu dir und dem, was du wirklich willst.', 'textarea'),
('hero.cta.label', 'Meinen Platz sichern', 'text'),
('hero.cta.note', 'Max. 11 Frauen &middot; 3 Coaches &middot; Ratenzahlung möglich', 'html'),
('hero.image.wide.src', 'assets/img/hero-tall.webp', 'image'),
('hero.image.tall.src', 'assets/img/hero-tall.webp', 'image'),
('hero.image.tall.alt', 'Drei Frauen von hinten am Feldrand oberhalb des Retreat-Anwesens bei Spabrücken', 'text'),
('hero.belt', 'Vier Tage &nbsp;·&nbsp; Max. 11 Frauen &nbsp;·&nbsp; 3 Coaches &nbsp;·&nbsp; Spabrücken, Rheinland-Pfalz', 'html'),
('einladung.rail', 'Kapitel 01', 'text'),
('einladung.eyebrow', 'Eine Einladung', 'text'),
('einladung.headline', 'Wann hast du dir das letzte Mal wirklich Zeit für dich genommen?', 'text'),
('einladung.body', '[{"text": "Nicht, um etwas abzuarbeiten oder das nächste Ziel zu erreichen. Sondern einfach, um wieder genauer hinzuhören."}, {"text": "B³ ist eine Einladung, für vier Tage Abstand vom Alltag zu nehmen: zu deinem Körper, deinen Gedanken, deiner Intuition und den Wünschen, die dabei manchmal leiser werden."}, {"text": "Vom 08.–11. Oktober schaffen wir inmitten der Natur einen Raum für Frauen, die wissen, wo sie stehen – und sich trotzdem bewusst Zeit für sich nehmen möchten."}, {"text": "Dich erwarten Yin Yoga und Breathwork, Astrologie und Frequenzarbeit, Reflexion und Struktur. Dazu gutes Essen, Natur, Gemeinschaft und genügend freie Zeit für das, was dir guttut."}]', 'json'),
('einladung.link.label', 'Das ganze Programm ansehen', 'text'),
('einladung.image.src', 'assets/img/detail-kerze.webp', 'image'),
('einladung.image.alt', 'Kerze und Lavendel auf einem Holzhocker im Retreat-Raum', 'text'),
('einladung.accent.title', 'Body. Mind. Soul.', 'text'),
('einladung.accent.text', 'Drei Perspektiven, die sich zu einer gemeinsamen Erfahrung verbinden.', 'textarea'),
('einladung.accent.said', 'B³ – gesprochen: Be free.', 'text'),
('bms.rail', 'Kapitel 02', 'text'),
('bms.eyebrow', 'Body. Mind. Soul.', 'text'),
('bms.headline', 'Das ist B³.', 'text'),
('bms.ruler', 'Drei Zugänge', 'text'),
('bms.intro', 'Wir sind Sophie, Sarah und Christina und bringen drei ganz unterschiedliche Perspektiven mit, die sich bei B³ miteinander verbinden.', 'textarea'),
('bms.cols', '[{"title": "Body", "sup": "1", "who": "Sarah", "text": "Sarah arbeitet mit dem Körper, dem Atem und unserer Wahrnehmung."}, {"title": "Soul", "sup": "2", "who": "Sophie", "text": "Sophie verbindet Astrologie, Energiearbeit und spirituelle Impulse."}, {"title": "Mind", "sup": "3", "who": "Christina", "text": "Christina bringt Klarheit, Reflexion und Struktur hinein und beschäftigt sich mit der Frage, wie wir unser Leben so gestalten können, dass das, was uns wirklich wichtig ist, darin auch seinen Platz findet."}]', 'json'),
('bms.outro', '[{"text": "Für uns gehören diese Ebenen zusammen. Denn das, was wir fühlen, was wir denken und wie wir unser Leben gestalten, lässt sich nicht immer voneinander trennen."}, {"text": "Genau aus dieser Verbindung ist B³ entstanden."}]', 'json'),
('bms.sign', 'Body. Mind. Soul. Be free.', 'text'),
('ablauf.rail', 'Kapitel 03', 'text'),
('ablauf.eyebrow', 'Donnerstag bis Sonntag', 'text'),
('ablauf.headline', 'Eine Reise zurück zu dir.', 'text'),
('ablauf.ruler', 'Der Bogen', 'text'),
('ablauf.intro', '[{"text": "Wir möchten diese vier Tage nicht wie ein klassisches Seminar gestalten, bei dem ein Programmpunkt auf den nächsten folgt."}, {"text": "Unsere Sessions bauen aufeinander auf, ohne dass wir jeden Moment deines Tages verplanen. Zwischen den gemeinsamen Zeiten bleibt bewusst Raum, damit du das Erlebte auch einfach einmal wirken lassen kannst."}]', 'json'),
('ablauf.image.src', 'assets/img/ablauf.webp', 'image'),
('ablauf.image.alt', 'Blick von der Terrasse über Felder und Wald', 'text'),
('ablauf.timeline', '[{"tag": "Donnerstag", "text": "Du darfst erst einmal ankommen und den Alltag langsam hinter dir lassen. Anreise ab 16:00 Uhr."}, {"tag": "Freitag", "text": "Wir tauchen gemeinsam tiefer ein und beschäftigen uns mit deinem Körper, deiner Wahrnehmung und deinen Bedürfnissen."}, {"tag": "Samstag", "text": "Mit unseren Experiences und rund um den Neumond gehen wir noch einmal tiefer."}, {"tag": "Sonntag", "text": "Wir lassen die gemeinsamen Tage ruhig ausklingen. Abreise bis 12:00 Uhr."}]', 'json'),
('ablauf.note', 'Denn am Ende sollst du nicht nach Hause fahren und erst einmal Urlaub von deinem Retreat brauchen.', 'textarea'),
('neumond.rail', 'Kapitel 04', 'text'),
('neumond.eyebrow', 'Mitten im Wochenende', 'text'),
('neumond.headline', 'Der Neumond als besonderer Moment', 'text'),
('neumond.ruler', 'Samstag', 'text'),
('neumond.intro', 'Mitten in unserem gemeinsamen Wochenende begleitet uns der Neumond und gibt uns einen schönen Anlass, noch einmal bewusster hinzuschauen.', 'textarea'),
('neumond.fragen', '[{"text": "Was brauche ich gerade wirklich?"}, {"text": "Was fühlt sich noch nach mir an?"}, {"text": "Wo wünsche ich mir Veränderung oder mehr Balance?"}, {"text": "Und welchen Dingen möchte ich in meinem Leben wieder mehr Raum geben?"}]', 'json'),
('neumond.outro', '[{"text": "Diese Fragen werden nicht in einer einzigen Session beantwortet. Sie dürfen sich durch unsere gemeinsamen Tage ziehen und aus ganz unterschiedlichen Perspektiven betrachtet werden."}, {"text": "Dabei geht es nicht darum, nach vier Tagen alles anders zu machen. Vielleicht geht es vielmehr darum, klarer zu sehen, was längst da ist und wieder mehr darauf zu vertrauen."}]', 'json'),
('exp.kapitel', 'Kapitel 05', 'text'),
('exp.eyebrow', 'Das Programm', 'text'),
('exp.headline', 'Deine B³ Experiences', 'text'),
('exp.ruler', 'Vier Zugänge', 'text'),
('exp.intro', 'Unsere Experiences greifen ineinander und begleiten dich über verschiedene Zugänge – über deinen Körper, deine innere Wahrnehmung und deine Gedanken.', 'textarea'),
('exp.items', '[{"image": {"src": "assets/img/exp-sarah.webp", "alt": "Sarah Bernhard mit gefalteten Händen auf der Terrasse am Feldrand", "height": 1250}, "who": "Mit Sarah", "title": "Yin Yoga &amp; Breathwork", "flip": "", "paragraphs": [{"text": "Wir starten gemeinsam mit ruhigem Yin Yoga in den Morgen. Zeit, um im Körper anzukommen, wahrzunehmen und bewusst in den Tag zu starten."}, {"text": "In einer gemeinsamen Breathwork Session schaffen wir Raum, tiefer zu fühlen, wahrzunehmen und dem zu begegnen, was sich gerade zeigen möchte."}, {"text": "Dabei geht es nicht darum, etwas zu erzwingen oder „wegzumachen“, sondern einen Raum zu schaffen, in dem du deinen Körper wieder wahrnehmen, zur Ruhe kommen und dich selbst ein Stück tiefer erfahren kannst."}], "second": {"who": "", "title": "", "paragraphs": []}}, {"image": {"src": "assets/img/exp-sophie.webp", "alt": "Sophie Christin Braun am Feldrand im späten Nachmittagslicht", "height": 1250}, "who": "Mit Sophie", "title": "Astro Energy Reading", "flip": " exp__item--flip", "paragraphs": [{"text": "Astrologie ist für Sophie keine Vorhersage, sondern ein Spiegel und eine Erinnerung."}, {"text": "Beim Retreat nimmt sie uns mit in ein Astro Energy Reading zu den aktuellen Energien – unter anderem zur Neumondenergie, zu Jupiter im Löwen sowie Saturn und Neptun im Widder."}, {"text": "Dabei geht es nicht darum, vorherzusagen, was passieren wird, sondern darum, welche Themen und Qualitäten wir gerade bewusst wahrnehmen und für uns nutzen dürfen."}], "second": {"who": "Mit Sophie", "title": "Solfeggio-Frequenz-Erinnerungs-Reise", "paragraphs": [{"text": "Sophie nimmt uns außerdem mit auf eine Reise zum Loslassen, Ankommen und Stillwerden. Begleitet von Solfeggio-Frequenzen und Energiearbeit entsteht ein Raum, in dem du dich zurücklehnen, wahrnehmen und wieder mehr bei dir und in der Verbindung zur Quelle ankommen darfst."}, {"text": "Denn manchmal brauchen wir keine weitere Antwort von außen, sondern die Ruhe, um wieder wahrzunehmen, was in uns längst da ist."}]}}, {"image": {"src": "assets/img/exp-christina.webp", "alt": "Christina am Feldrand im späten Nachmittagslicht", "height": 1250}, "who": "Mit Christina", "title": "Mit Struktur zu mehr Leichtigkeit", "flip": " exp__item--flip", "paragraphs": [{"text": "Du kannst alles wollen. Selbstverwirklichung, Business, Familie, Partnerschaft, Zeit für dich, Erfolg, Ruhe und Wachstum."}, {"text": "Die spannende Frage ist nicht, ob all das zusammenpassen darf, sondern wie du dein Leben so gestalten kannst, dass die Dinge, die dir wirklich wichtig sind, darin auch ihren Platz bekommen."}, {"text": "In unserer gemeinsamen Session beschäftigen wir uns deshalb nicht mit starren Regeln, perfekten Routinen oder dem nächsten durchgetakteten Wochenplan. Wir schauen auf eine intuitive und lebendige Struktur, die zu dir, deinen Bedürfnissen und deinem Leben passt."}, {"text": "Eine Struktur, die dich unterstützt, statt dich einzuengen – und dadurch mehr Leichtigkeit möglich macht."}], "second": {"who": "", "title": "", "paragraphs": []}}]', 'json'),
('freizeit.frieze.src', 'assets/img/fries-hof.webp', 'image'),
('freizeit.frieze.alt', 'Zufahrt und Hof des Anwesens, gesäumt von Zypressen', 'text'),
('freizeit.kapitel', 'Kapitel 06', 'text'),
('freizeit.eyebrow', 'Raum dazwischen', 'text'),
('freizeit.headline', 'Genug Zeit für dich', 'text'),
('freizeit.p1', 'Zu einem Retreat gehört für uns nicht nur das, was wir gemeinsam machen, sondern genauso die Zeit dazwischen.', 'textarea'),
('freizeit.p2', 'Deshalb planen wir bewusst längere Pausen und freie Zeit ein. Du kannst durch Wald und Felder spazieren, dich mit einem Buch zurückziehen, deine Gedanken aufschreiben, Zeit mit den anderen Frauen verbringen oder einfach irgendwo auf dem Gelände sitzen und nichts tun.', 'textarea'),
('freizeit.pullout', 'Alle unsere Experiences sind freiwillig.', 'text'),
('freizeit.p3', 'Wenn du an einem Morgen länger schlafen möchtest oder während einer Session merkst, dass du gerade lieber für dich sein möchtest, ist das genauso in Ordnung.', 'textarea'),
('freizeit.small', 'Während ausgewählter freier Zeitfenster kannst du außerdem persönliche 1:1 Sessions mit Sophie, Sarah oder Christina gegen Aufpreis buchen.', 'textarea'),
('freizeit.cta', 'Ich möchte dabei sein', 'text'),
('freizeit.belt', 'Du kommst an. Du musst nichts mitbringen außer dir selbst.', 'text'),
('ort.kapitel', 'Kapitel 07', 'text'),
('ort.eyebrow', 'Spabrücken | Rheinland-Pfalz', 'text'),
('ort.headline', 'Unser Retreat-Ort', 'text'),
('ort.map.line1', 'Spabrücken, Landkreis Bad Kreuznach.', 'text'),
('ort.p1', 'Unser Retreat findet auf einem großzügigen Anwesen in Spabrücken statt. Abgelegen vom Trubel und umgeben von Feldern, Wald und kleinen Wegen ist es ein Ort, an dem man erstaunlich schnell ein bisschen langsamer wird.', 'textarea'),
('ort.p2', 'Das Herzstück unseres Retreats ist eine große, moderne Remise. Hier finden viele unserer Experiences statt, hier essen wir gemeinsam und wahrscheinlich entstehen hier auch einige der Gespräche, die man vorher nicht planen kann.', 'textarea'),
('ort.p3', 'Bei schönem Wetter verbringen wir die Abende draußen auf der großen Holzterrasse. Von dort blickt man weit über die Landschaft und kann den Sonnenuntergang genießen, während auf dem Holzgrill unser Abendessen zubereitet wird.', 'textarea'),
('ort.p4', 'Und wenn du zwischendurch raus möchtest, gehst du einfach los. Rund um das Anwesen führen Feld- und Waldwege durch die Umgebung.', 'textarea'),
('ort.mosaic[0].src', 'assets/img/ort-terrasse.webp', 'image'),
('ort.mosaic[0].alt', 'Überdachte Terrasse mit langem Tisch, dahinter offene Felder', 'text'),
('ort.mosaic[1].src', 'assets/img/ort-sonne.webp', 'image'),
('ort.mosaic[1].alt', 'Sonnenlicht durch die Baumkronen am Rand des Grundstücks', 'text'),
('ort.mosaic[2].src', 'assets/img/ort-anwesen.webp', 'image'),
('ort.mosaic[2].alt', 'Das Anwesen mit Zypressenreihe und Sitzgruppe', 'text'),
('ort.mosaic[3].src', 'assets/img/ort-remise.webp', 'image'),
('ort.mosaic[3].alt', 'Zufahrt zur Remise', 'text'),
('ort.mosaic[4].src', 'assets/img/ort-terrasse2.webp', 'image'),
('ort.mosaic[4].alt', 'Lounge auf der Terrasse mit Blick über die Felder', 'text'),
('ort.mosaic[5].src', 'assets/img/ort-eingang.webp', 'image'),
('ort.mosaic[5].alt', 'Eingangsbereich des Anwesens', 'text'),
('ort.mosaic[6].src', 'assets/img/ort-saeule.webp', 'image'),
('ort.mosaic[6].alt', 'Überdachter Außenbereich mit Blick ins Tal', 'text'),
('ort.mosaic[7].src', 'assets/img/ort-haus.webp', 'image'),
('ort.mosaic[7].alt', 'Überdachter Balkon mit Sitzgelegenheit', 'text'),
('kulinarik.kapitel', 'Kapitel 08', 'text'),
('kulinarik.eyebrow', 'Frühstück &amp; Holzgrill', 'text'),
('kulinarik.headline', 'Gutes Essen und lange Abende', 'text'),
('kulinarik.ruler', 'Am Tisch', 'text'),
('kulinarik.p1', 'Freitag, Samstag und Sonntag starten wir gemeinsam mit einem reichhaltigen Frühstück in den Tag. Es gibt unter anderem frische Brötchen, Aufschnitt, Obst, Porridge und weitere warme Speisen.', 'textarea'),
('kulinarik.p2', 'Auch zwischendurch steht im Haus immer etwas zum Snacken bereit.', 'textarea'),
('kulinarik.p3', 'Am Abend kommen wir wieder gemeinsam zum Essen zusammen. Wenn das Wetter mitspielt, sitzen wir draußen auf der Holzterrasse, essen frisch zubereitete Speisen vom Holzgrill und lassen den Tag gemeinsam ausklingen.', 'textarea'),
('kulinarik.tagline', 'Bei der Buchung wählbar: normale oder vegetarische Verpflegung', 'text'),
('haus.frieze.image.src', 'assets/img/haus-fries.webp', 'image'),
('haus.frieze.image.alt', 'Gemeinschaftsbereich mit Essplatz und Sitzlandschaft', 'text'),
('haus.rail', 'Kapitel 09', 'text'),
('haus.eyebrow', 'Unterbringung &amp; Preise', 'text'),
('haus.headline', 'Dein Zuhause für diese vier Tage', 'text'),
('haus.sub', 'Du kannst zwischen zwei Möglichkeiten der Unterbringung wählen.', 'textarea'),
('haus.shared.label', 'Shared House', 'text'),
('haus.shared.headline', 'Gemeinsam wohnen, gemeinsam erleben.', 'text'),
('haus.shared.text', 'Unser ca. 150 m² großer Neubau verbindet moderne Einrichtung mit rustikaler Holzoptik und bietet Platz für bis zu 11 Frauen.', 'textarea'),
('haus.shared.feats', '[{"text": "4 Schlafzimmer"}, {"text": "2- und 3-Bettzimmer mit Einzelbetten"}, {"text": "Gemeinschaftsraum"}, {"text": "Küchenzeile"}, {"text": "Badezimmer"}, {"text": "separates WC"}]', 'json'),
('haus.shared.note', 'Die Zimmer und Betten werden von uns zugeteilt. Eine Vorauswahl ist nicht möglich.', 'textarea'),
('haus.shared.galerie', '[{"src": "assets/img/haus-g1.webp", "alt": "Schlafzimmer mit gepolstertem Kopfteil und bodentiefem Fenster"}, {"src": "assets/img/haus-g2.webp", "alt": "Zweites Schlafzimmer mit Blick ins Grüne"}, {"src": "assets/img/haus-g3.webp", "alt": "Gemeinschaftsraum mit Küchenzeile, Essplatz und Sitzlandschaft"}, {"src": "assets/img/haus-g4.webp", "alt": "Badezimmer mit ebenerdiger Dusche"}]', 'json'),
('haus.shared.price', '1.549&nbsp;€', 'text'),
('haus.shared.price_note', 'pro Person &middot; 3 Übernachtungen, Verpflegung und alle regulären B³ Experiences inklusive. Ratenzahlung möglich.', 'textarea'),
('haus.shared.cta', 'Meinen Platz sichern', 'text'),
('haus.shared.url', '', 'url'),
('haus.friends.label', 'Friends Special', 'text'),
('haus.friends.badge', 'Exklusiv', 'text'),
('haus.friends.headline', 'Euer eigener Rückzugsort.', 'text'),
('haus.friends.text', 'Wenn ihr zu zweit kommt und euch während des Retreats mehr Privatsphäre gönnen möchtet, könnt ihr unser exklusives Apartment buchen. Auf ca. 150 m² habt ihr jede Menge Platz nur für euch und einen wunderschönen Blick über die Landschaft.', 'textarea'),
('haus.friends.feats', '[{"text": "Schlafzimmer mit Doppelbett"}, {"text": "großzügiges Wohnzimmer"}, {"text": "eigene Küchenzeile"}, {"text": "Badezimmer"}, {"text": "separates WC"}, {"text": "großer Balkon mit weitem Ausblick"}]', 'json'),
('haus.friends.note', 'Ihr seid bei allen gemeinsamen Experiences und Mahlzeiten dabei und könnt euch zwischendurch jederzeit in eure eigenen vier Wände zurückziehen.', 'textarea'),
('haus.friends.galerie', '[{"src": "assets/img/friends-g1.webp", "alt": "Schlafzimmer des Apartments mit Doppelbett"}, {"src": "assets/img/friends-g2.webp", "alt": "Wohnzimmer des Apartments mit eigener Küchenzeile"}, {"src": "assets/img/friends-g3.webp", "alt": "Balkon mit weitem Blick über die Landschaft"}, {"src": "assets/img/friends-g4.webp", "alt": "Überdachter Außenbereich am Apartment"}]', 'json'),
('haus.friends.price', '3.950&nbsp;€', 'text'),
('haus.friends.price_note', 'für 2 Personen &middot; 3 Übernachtungen, Verpflegung und alle regulären B³ Experiences inklusive. Ratenzahlung möglich.', 'textarea'),
('haus.friends.cta', 'Friends Special sichern', 'text'),
('haus.friends.url', '', 'url'),
('inkl.eyebrow', 'Im Preis enthalten', 'text'),
('inkl.headline', 'Was ist inklusive?', 'text'),
('inkl.intro', 'Mit deiner Buchung ist fast alles abgedeckt, was du während der gemeinsamen Tage brauchst:', 'textarea'),
('inkl.items', '[{"text": "3 Übernachtungen"}, {"text": "Frühstück am Freitag, Samstag und Sonntag"}, {"text": "gemeinsame Abendessen"}, {"text": "Snacks für zwischendurch"}, {"text": "Yin Yoga"}, {"text": "Gruppen-Breathwork"}, {"text": "Astro Energy Reading"}, {"text": "Solfeggio-Frequenz-Erinnerungs-Reise"}, {"text": "Gruppen-Session „Mit Struktur zu mehr Leichtigkeit“"}, {"text": "unsere gemeinsame Zeit rund um den Neumond"}, {"text": "Nutzung der Retreat- und Gemeinschaftsbereiche"}, {"text": "ausreichend freie Zeit für dich"}]', 'json'),
('inkl.excluded_label', 'Nicht enthalten', 'text'),
('inkl.excluded_text', 'Deine individuelle An- und Abreise sowie optional buchbare 1:1 Sessions.', 'textarea'),
('team.rail', 'Kapitel 10', 'text'),
('team.eyebrow', 'Sophie &middot; Sarah &middot; Christina', 'text'),
('team.headline', 'Die drei Frauen hinter B³', 'text'),
('team.intro', 'Drei Persönlichkeiten, drei unterschiedliche Welten und ziemlich unterschiedliche Wege haben uns hierhergebracht. Was uns verbindet, ist die Überzeugung, dass wir uns und unser Leben nicht in einzelne Schubladen aufteilen müssen.', 'textarea'),
('team.sophie.image.src', 'assets/img/sophie.webp', 'image'),
('team.sophie.image.alt', 'Sophie Christin Braun am Feldrand', 'text'),
('team.sophie.name', 'Sophie Christin Braun', 'text'),
('team.sophie.craft', 'Astrologie | Energiearbeit | spirituelle &amp; mediale Impulse', 'text'),
('team.sophie.text1', 'Ich bin Sophie – neugierig, intuitiv, manchmal ziemlich tiefgründig und definitiv ein kleiner Freigeist.', 'textarea'),
('team.sophie.text2', 'Ich war noch nie besonders gut darin, mich in Schubladen stecken zu lassen. Ich mag kein Schwarz-Weiß-Denken und keine fertigen Antworten.', 'textarea'),
('team.sophie.accent', 'Aber warum eigentlich? Muss das wirklich so sein?', 'textarea'),
('team.sophie.text3', 'Genau diese Freiheit, selbst zu denken, zu fühlen und den eigenen Weg zu gehen, möchte ich auch in meine Arbeit mitgeben. Meine Arbeit verbindet Astrologie, Energiearbeit und spirituelle sowie mediale Impulse. Im Mittelpunkt steht für mich dabei immer die Verbindung zur Quelle, zu Gott und zu unserer eigenen inneren Wahrheit.', 'textarea'),
('team.sophie.text4', 'Ich freue mich sehr auf echte Begegnungen, tiefe Gespräche, kleine Aha-Momente und darauf, diese besondere Zeit miteinander zu erleben.', 'textarea'),
('team.sarah.image.src', 'assets/img/sarah.webp', 'image'),
('team.sarah.image.alt', 'Sarah Bernhard am Feldrand', 'text'),
('team.sarah.name', 'Sarah Bernhard', 'text'),
('team.sarah.craft', 'Yin Yoga | Breathwork | Bodywork', 'text'),
('team.sarah.text1', 'Ich bin Sarah und begleite Menschen dabei, wieder mehr in Kontakt mit sich selbst, ihrem Körper und dem eigenen Erleben zu kommen.', 'textarea'),
('team.sarah.text2', 'Mir geht es dabei nicht darum, etwas zu erzwingen oder „wegzumachen“, sondern einen Raum zu schaffen, in dem du deinen Körper wieder wahrnehmen, zur Ruhe kommen und dich selbst ein Stück tiefer erfahren kannst.', 'textarea'),
('team.christina.image.src', 'assets/img/christina.webp', 'image'),
('team.christina.image.alt', 'Christina am Feldrand', 'text'),
('team.christina.name', 'Christina', 'text'),
('team.christina.craft', 'Strategie | Business | Struktur', 'text'),
('team.christina.text1', 'Ich bin Christina – kreative Seele, Unternehmerin und ziemlich schlecht darin, mich mit einem „entweder oder“ zufriedenzugeben.', 'textarea'),
('team.christina.accent', 'Ich will alles.', 'textarea'),
('team.christina.text2', 'Ich möchte mich in meinem Business verwirklichen, meine Familie und Partnerschaft lieben und leben, erfolgreich sein, frei sein und trotzdem genügend Zeit für die Menschen und Dinge haben, die mir wichtig sind.', 'textarea'),
('team.christina.text3', 'Mit klassischer Work-Life-Balance konnte ich deshalb noch nie besonders viel anfangen. Mein Business steht für mich nicht auf der einen und mein Leben auf der anderen Seite. Es ist ein Teil meines Lebens, den ich liebe und den ich genauso bewusst gestalten möchte wie alle anderen Bereiche.', 'textarea'),
('team.christina.text4', 'Ich glaube daran, dass die Dinge, die uns wichtig sind, gleichzeitig Platz haben dürfen. Nicht immer zu gleichen Teilen und ganz sicher nicht immer perfekt. Aber ohne uns selbst dabei ständig auf später zu verschieben.', 'textarea'),
('team.christina.text5', 'Dafür braucht es Struktur. Nur eben keine starren Regeln und keinen Kalender, der jede Minute kontrolliert. Ich arbeite mit einer intuitiven, lebendigen Struktur, die sich dem Leben anpassen darf und uns dabei hilft, unsere Prioritäten tatsächlich zu leben.', 'textarea'),
('team.christina.text6', 'Denn Selbstverwirklichung bedeutet für mich nicht, immer mehr zu schaffen. Es bedeutet, ein Leben aufzubauen, das wirklich zu mir gehört.', 'textarea'),
('fuerwen.rail', 'Kapitel 11', 'text'),
('fuerwen.eyebrow', 'Ausschließlich für Frauen', 'text'),
('fuerwen.headline', 'Ist B³ für dich?', 'text'),
('fuerwen.body', '[{"text": "B³ ist für Frauen, die grundsätzlich wissen, wer sie sind und wohin sie möchten. Frauen mit Wünschen, Zielen und Ideen, die sich ganz bewusst ein paar Tage Zeit nehmen möchten, um wieder genauer hinzuhören."}, {"text": "Vielleicht hast du dir bereits ein Leben aufgebaut, das du sehr magst, und trotzdem gibt es Fragen, die im Alltag zu wenig Raum bekommen."}]', 'json'),
('fuerwen.image.src', 'assets/img/fuerwen-blick.webp', 'image'),
('fuerwen.image.alt', 'Blick von der Terrasse über Bäume und Felder', 'text'),
('fuerwen.fragen', '[{"text": "Was will ich gerade wirklich?"}, {"text": "Was brauche ich mehr und wovon vielleicht weniger?"}, {"text": "Was fühlt sich noch nach mir an?"}, {"text": "Wo möchte ich etwas verändern?"}, {"text": "Was möchte ich genauso behalten, wie es ist?"}]', 'json'),
('fuerwen.fazit', 'Du musst bei B³ keine neue Version von dir werden. Es geht vielmehr darum, wieder näher an das heranzukommen, was längst zu dir gehört.', 'textarea'),
('fuerwen.cta.label', 'Ja, ich möchte dabei sein', 'text'),
('fuerwen.cta.note', '08.–11. Oktober 2026 &middot; Spabrücken &middot; Ratenzahlung möglich', 'text'),
('buchung.url', '', 'url'),
('buchung.bg.src', 'assets/img/buchung-bg.webp', 'image'),
('buchung.titel', 'B³ Retreat Oktober 2026', 'text'),
('buchung.ort', 'Spabrücken, Rheinland-Pfalz', 'text'),
('buchung.termine', '[{"label": "Anreise", "zeit": "Donnerstag, 08.10.2026 ab 16:00 Uhr"}, {"label": "Abreise", "zeit": "Sonntag, 11.10.2026 bis 12:00 Uhr"}]', 'json'),
('buchung.preise', '[{"label": "Shared House", "preis": "1.549 €", "hinweis": "pro Person"}, {"label": "Friends Special", "preis": "3.950 €", "hinweis": "für 2 Personen"}]', 'json'),
('buchung.hinweis', 'Unterkunft, Verpflegung und alle regulären B³ Experiences inklusive. Ratenzahlung möglich.', 'textarea'),
('buchung.cta.label', 'Meinen Platz sichern', 'text'),
('buchung.fine', 'Zahlung über unseren externen Anbieter Tentary. AGB und Stornierungsbedingungen sind vor Abschluss der Buchung vollständig einsehbar.', 'textarea'),
('faq.rail', 'Kapitel 12', 'text'),
('faq.eyebrow', 'Gut zu wissen', 'text'),
('faq.headline', 'Häufige Fragen', 'text'),
('faq.spalte1', '[{"frage": "Muss ich an allen Experiences teilnehmen?", "antwort": "<p>Nein. Alle Experiences sind freiwillig. Wenn du eine Session auslassen und stattdessen spazieren gehen, schlafen, lesen oder einfach Zeit für dich verbringen möchtest, ist das vollkommen in Ordnung.</p>"}, {"frage": "Gibt es genügend Freizeit?", "antwort": "<p>Ja. Wir planen bewusst freie Zeiten zwischen den gemeinsamen Experiences ein, damit du das Erlebte wirken lassen und das Retreat in deinem eigenen Tempo genießen kannst.</p>"}, {"frage": "Kann ich eine persönliche 1:1 Session buchen?", "antwort": "<p>Ja. In ausgewählten freien Zeitfenstern kannst du zusätzliche 1:1 Sessions mit Sophie, Sarah oder Christina buchen. Diese sind nicht im Retreat-Preis enthalten und werden separat berechnet.</p>"}, {"frage": "Ist das Retreat ausschließlich für Frauen?", "antwort": "<p>Ja. Dieses B³ Retreat richtet sich ausschließlich an Frauen.</p>"}, {"frage": "Ist die Verpflegung inklusive?", "antwort": "<p>Ja. Frühstück, gemeinsame Abendessen und Snacks für zwischendurch sind inklusive. Bei der Buchung kannst du zwischen normaler und vegetarischer Verpflegung wählen.</p>"}, {"frage": "Was ist bei Allergien oder Unverträglichkeiten?", "antwort": "\\n            <p>Wir können keine individuell allergenfreie Zubereitung und keinen vollständigen Ausschluss von Kreuzkontaminationen gewährleisten.</p>\\n            <p>Wenn du Allergien oder Unverträglichkeiten hast, informiere uns bitte vorab und achte vor Ort eigenverantwortlich darauf, welche Lebensmittel für dich geeignet sind.</p>\\n          "}, {"frage": "Kann ich mein Zimmer auswählen?", "antwort": "<p>Nein. Im Shared House erfolgt die Unterbringung in 2- und 3-Bettzimmern mit Einzelbetten. Die Zimmer und Betten werden von uns zugeteilt.</p>"}]', 'json'),
('faq.spalte2', '[{"frage": "Kann ich auch alleine kommen?", "antwort": "<p>Natürlich. Du musst niemanden kennen oder gemeinsam mit jemandem anreisen. Du wirst während der vier Tage Teil unserer kleinen B³ Gruppe sein und hast gleichzeitig jederzeit die Möglichkeit, dich zurückzuziehen.</p>"}, {"frage": "Kann ich mit einer Freundin kommen?", "antwort": "<p>Ja. Ihr könnt entweder jeweils einen Platz im Shared House buchen oder gemeinsam unser Friends Special wählen. Damit steht euch das ca. 150 m² große Apartment exklusiv zur Verfügung.</p>"}, {"frage": "Ist Ratenzahlung möglich?", "antwort": "<p>Ja. Die verfügbaren Möglichkeiten zur Ratenzahlung kannst du direkt im Buchungsprozess auswählen.</p>"}, {"frage": "Wie funktioniert die Anreise?", "antwort": "<p>Die An- und Abreise organisierst du eigenständig und sie ist nicht im Retreat-Preis enthalten. Die genaue Adresse in Spabrücken sowie weitere Informationen erhältst du rechtzeitig vor dem Retreat.</p>"}, {"frage": "Wann beginnt und endet das Retreat?", "antwort": "<p>Die Anreise ist am Donnerstag, den 08. Oktober 2026 ab 16:00 Uhr möglich. Am Sonntag, den 11. Oktober 2026 erfolgt die Abreise vormittags bis spätestens 12:00 Uhr.</p>"}, {"frage": "Gibt es einen Hund auf dem Gelände?", "antwort": "<p>Ja. Auf dem Anwesen lebt ein großer Wachhund. Er befindet sich in einem eigenen, gesicherten Bereich und läuft während des Retreats nicht frei auf dem Gelände herum. Diese Information ist vor allem wichtig, wenn du Angst vor großen Hunden hast.</p>"}, {"frage": "Was passiert, wenn ich stornieren muss?", "antwort": "\\n            <p>Deine Buchung ist verbindlich. Für eine Stornierung gelten unsere zum Zeitpunkt deiner Buchung gültigen Stornierungsbedingungen und <a class=\\"link\\" href=\\"agb.html\\">AGB</a>, die du vor Abschluss deiner Buchung vollständig einsehen kannst.</p>\\n            <p>Für unvorhergesehene Fälle empfehlen wir dir, eine passende Reiserücktrittsversicherung abzuschließen.</p>\\n          "}]', 'json'),
('foot.brand.tagline', 'Body. Mind. Soul.<br>Yoga &middot; Astro &middot; Business', 'html'),
('foot.brand.dateline', '08.&ndash;11. Oktober 2026<br>Spabrücken, Rheinland-Pfalz', 'html'),
('foot.nav.retreat.label', 'Retreat', 'text'),
('foot.nav.retreat.programm', 'Programm', 'text'),
('foot.nav.retreat.ort', 'Der Ort', 'text'),
('foot.nav.retreat.unterkunft', 'Unterkunft &amp; Preise', 'text'),
('foot.nav.retreat.team', 'Über uns', 'text'),
('foot.nav.retreat.faq', 'Häufige Fragen', 'text'),
('foot.nav.legal.label', 'Rechtliches', 'text'),
('foot.nav.legal.impressum', 'Impressum', 'text'),
('foot.nav.legal.datenschutz', 'Datenschutz', 'text'),
('foot.nav.legal.agb', 'AGB', 'text'),
('foot.nav.legal.kontakt', 'Kontakt', 'text'),
('foot.nav.legal.consent', 'Cookie-Einstellungen', 'text'),
('foot.booking.label', 'Buchung', 'text'),
('foot.booking.prices', 'Shared House ab 1.549 &euro; pro Person<br>Friends Special 3.950 &euro; für zwei', 'html'),
('foot.booking.cta', 'Meinen Platz sichern', 'text'),
('foot.legal.line', 'B³ Retreats &middot; Christina Brumm &middot; An den Nahewiesen 20, 55450 Langenlonsheim', 'text'),
('foot.legal.note', 'Buchung und Zahlungsabwicklung über Tentary', 'text'),
('bar.price', 'Shared House ab 1.549 €', 'text'),
('bar.cta', 'Platz sichern', 'text'),
('consent.eyebrow', 'Cookies', 'text'),
('consent.text', 'Wir setzen nur technisch notwendige Cookies. Optionale Cookies für Statistik oder Marketing
         erst mit deiner Zustimmung — mehr dazu in der <a class="link" href="datenschutz.html">Datenschutzerklärung</a>.', 'html'),
('consent.btn_necessary', 'Nur notwendige', 'text'),
('consent.btn_all', 'Alle akzeptieren', 'text'),
('danke.meta.title', 'Du bist dabei! | B³ Retreats', 'text'),
('danke.eyebrow', 'Buchung bestätigt', 'text'),
('danke.headline', 'Du bist dabei! ♡', 'html'),
('danke.lead', 'Dein Platz beim B³ Retreat ist für dich reserviert.', 'html'),
('danke.intro', '[{"text": "Wie schön, dass du dich für diese besonderen Tage entschieden hast. Wir freuen uns riesig darauf, dich beim B³ Retreat willkommen zu heißen und gemeinsam eine unvergessliche Zeit zu erleben."}, {"text": "Jetzt darf die Vorfreude beginnen. ♡"}]', 'json'),
('danke.image.src', 'assets/img/hero-tall.webp', 'image'),
('danke.image.alt', 'Christina, Sophie und Sarah vom B³ Retreat', 'text'),
('danke.next.title', 'Wie geht es jetzt weiter?', 'text'),
('danke.next.body', '[{"text": "In den nächsten Stunden erhältst du von uns eine persönliche E-Mail mit allen wichtigen Informationen zu deinem Retreat."}, {"text": "Darin findest du alles, was du für die nächsten Schritte wissen musst."}]', 'json'),
('danke.ask.title', 'Eine kleine Sache brauchen wir noch von dir', 'text'),
('danke.ask.text', 'Bitte antworte direkt auf unsere E-Mail und teile uns mit, welche Verpflegung du während des Retreats möchtest:', 'html'),
('danke.ask.options', '[{"text": "Vegetarisch"}, {"text": "Mit Fleisch &amp; Fisch"}]', 'json'),
('danke.ask.note', 'So können wir deine Verpflegung entsprechend einplanen. Solltest du die E-Mail nicht direkt finden, wirf bitte auch einen Blick in deinen Spam-Ordner.', 'html'),
('danke.outro.title', 'Das war’s für den Moment.', 'text'),
('danke.outro.body', '[{"text": "Alles Weitere bekommst du persönlich von uns per E-Mail. Bis dahin musst du nichts weiter tun – außer dich auf deine Auszeit zu freuen."}, {"text": "Wir freuen uns auf dich!"}]', 'json'),
('danke.sign', 'Christina &amp; das B³ Retreat Team', 'html'),
('danke.cta', 'Zur Startseite', 'text')
ON DUPLICATE KEY UPDATE `v` = VALUES(`v`), `type` = VALUES(`type`);
